//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieAppDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_NumberUsersLike
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdMovie { get; set; }
        public Nullable<bool> IsLike { get; set; }
        public Nullable<System.DateTime> LikeDate { get; set; }
    
        public virtual MV_MOVIE MV_MOVIE { get; set; }
        public virtual PS_USERS PS_USERS { get; set; }
    }
}
